// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8DuZlAisTv7k-hUryU4iNr8PeDKATG4c',
    appId: '1:495543204481:web:918f6688344b3f9deeab80',
    messagingSenderId: '495543204481',
    projectId: 'rainsave-hackathon',
    authDomain: 'rainsave-hackathon.firebaseapp.com',
    storageBucket: 'rainsave-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmGEwEgzlcvi4lP01AxD49yy7GjqShCTo',
    appId: '1:495543204481:android:4a7a6a136e971b95eeab80',
    messagingSenderId: '495543204481',
    projectId: 'rainsave-hackathon',
    storageBucket: 'rainsave-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8DuZlAisTv7k-hUryU4iNr8PeDKATG4c',
    appId: '1:495543204481:web:d43c13b49d0c1e9deeab80',
    messagingSenderId: '495543204481',
    projectId: 'rainsave-hackathon',
    authDomain: 'rainsave-hackathon.firebaseapp.com',
    storageBucket: 'rainsave-hackathon.firebasestorage.app',
  );
}
